#!/usr/bin/env bash
if test -r "$SSH_AUTH_SOCK" -a "$SSH_AUTH_SOCK" != "$HOME/.ssh/ssh_auth_sock" ; then
    OLD_SSH_AUTH_SOCK="$SSH_AUTH_SOCK"
    ln -sf $SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
    echo Syminked ${HOME}/.ssh/ssh_auth_sock to $OLD_SSH_AUTH_SOCK >&2
fi

# Set up X11 when forwarding
# Cribbed from sshd manpage
if read proto cookie && [ -n "$DISPLAY" ]; then
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
                # X11UseLocalhost=yes
                echo add unix:`echo $DISPLAY |
                    cut -c11-` $proto $cookie
        else
                # X11UseLocalhost=no
                echo add $DISPLAY $proto $cookie
        fi | xauth -q -
fi
